[package]
name = "shared"
version = "0.1.0"
edition = "2021"

# [lib]
# path = "src/be_api.rs"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
prometheus = "0.13"
lazy_static = "1.4" 
chrono = "0.4" 